name: Gatsby Deploy

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "sergey.vodwood@gmail.com"
          git config --global user.name "svodwood"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
          nvm install 18.12.1
          nvm use 18.12.1
          npm install
      - name: Deploy
        run: npm run deploy:ci