name: Gatsby Deploy

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "sergey.vodwood@gmail.com"
          git config --global user.name "svodwood"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm install
      - name: Deploy
        run: npm run deploy:ci